package com.gultekinahmetabdullah.trainvoc.audio

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Audio cache entity for storing TTS audio files
 * Caches audio to reduce API calls and improve performance
 */
@Entity(
    tableName = "audio_cache",
    indices = [
        Index(value = ["word_id"]),
        Index(value = ["last_accessed"])
    ]
)
data class AudioCache(
    @PrimaryKey
    @ColumnInfo(name = "word_id")
    val wordId: String,

    @ColumnInfo(name = "word_text")
    val wordText: String,

    @ColumnInfo(name = "language")
    val language: String = "en",  // ISO language code

    @ColumnInfo(name = "tts_generated")
    val ttsGenerated: Boolean = true,  // true if generated by TTS, false if pre-recorded

    @ColumnInfo(name = "cached_file_path")
    val cachedFilePath: String?,  // Local file path

    @ColumnInfo(name = "file_size_bytes")
    val fileSizeBytes: Long = 0,

    @ColumnInfo(name = "created_at")
    val createdAt: Long = System.currentTimeMillis(),

    @ColumnInfo(name = "last_accessed")
    val lastAccessed: Long = System.currentTimeMillis(),

    @ColumnInfo(name = "access_count")
    val accessCount: Int = 0,

    @ColumnInfo(name = "audio_url")
    val audioUrl: String? = null  // Remote URL if available
)
