-- ============================================================================
-- trainvoc  —  DDL for the primary (gameplay + user) database
-- ============================================================================
-- This script creates the PRIMARY-database schema and NOTHING ELSE. It is
-- DDL-only on purpose: every row is written by the application at runtime
-- (users register, games are played, the Android client syncs progress/SRS),
-- so there is no seed data here.
--
-- Mounted by docker-compose as /docker-entrypoint-initdb.d for the `trainvoc`
-- container, so the schema exists before Spring Boot connects. Column names and
-- types match the JPA entities in
-- com.rollingcatsoftware.trainvocmultiplayerapplication.model exactly, so the
-- app can run with Hibernate ddl-auto=validate against it. Regenerated for the
-- v18 re-key (#96/#100): the old script only covered the four gameplay tables
-- (game_room/player/question/player_answer) with drifted types — this adds the
-- eight user/progress/SRS tables and corrects the gameplay types.
--
-- Type mapping (Hibernate 7 / PostgreSQL dialect): Long/long -> BIGINT,
-- int/Integer -> INTEGER, boolean/Boolean -> BOOLEAN, float -> REAL,
-- double -> DOUBLE PRECISION, String -> VARCHAR(length|255), enum(STRING) ->
-- VARCHAR, enum(ORDINAL) -> INTEGER, LocalDateTime -> TIMESTAMP, @Version Long ->
-- BIGINT, Instant -> TIMESTAMP WITH TIME ZONE. Nullability/uniques/indexes mirror
-- the @Column/@Table/@Index annotations (ddl-auto=validate itself only checks
-- tables, columns and types).
--
-- LOGICAL cross-database FKs: `word_id` columns reference `words.id` in the OTHER
-- (trainvoc-words) database, so they carry NO SQL foreign key here — only a real
-- FK where both ends live in this database (mostly `user_id` -> users.id).
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Identity / users (User + its user_roles @ElementCollection)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username           VARCHAR(50)  NOT NULL,
    email              VARCHAR(100) NOT NULL,
    password           VARCHAR(255) NOT NULL,
    display_name       VARCHAR(100),
    firebase_uid       VARCHAR(128),
    auth_provider      VARCHAR(20)  NOT NULL,
    email_verified     BOOLEAN      NOT NULL,
    enabled            BOOLEAN      NOT NULL,
    account_non_locked BOOLEAN      NOT NULL,
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP,
    last_login         TIMESTAMP,
    total_games_played INTEGER      NOT NULL,
    total_score        INTEGER      NOT NULL,
    games_won          INTEGER      NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- Unique indexes as declared on @Table(indexes = ...); each column is also
-- @Column(unique = true), enforced here once via the named unique index.
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_email ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_username ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_firebase_uid ON users (firebase_uid);

-- User.roles: @ElementCollection of the Role enum stored as strings.
CREATE TABLE IF NOT EXISTS user_roles
(
    user_id BIGINT NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON user_roles (user_id);

-- ---------------------------------------------------------------------------
-- Gameplay (GameRoom / Player / Question / PlayerAnswer)
-- ---------------------------------------------------------------------------

-- GameRoom: currentState is @Enumerated(ORDINAL) -> INTEGER; version is @Version.
CREATE TABLE IF NOT EXISTS game_room
(
    room_code              VARCHAR(32) NOT NULL,
    version                BIGINT,
    current_question_index INTEGER,
    started                BOOLEAN,
    host_id                VARCHAR(255),
    question_duration      INTEGER,
    option_count           INTEGER,
    level                  VARCHAR(255),
    total_question_count   INTEGER,
    last_used              TIMESTAMP,
    hashed_password        VARCHAR(128),
    current_state          INTEGER,
    state_start_time       TIMESTAMP,
    CONSTRAINT pk_game_room PRIMARY KEY (room_code)
);

-- Player: room is @ManyToOne -> game_room(room_code) (VARCHAR(32) to match the PK).
CREATE TABLE IF NOT EXISTS player
(
    id                              VARCHAR(255) NOT NULL,
    version                         BIGINT,
    room_code                       VARCHAR(32),
    name                            VARCHAR(255),
    score                           INTEGER,
    correct_count                   INTEGER,
    wrong_count                     INTEGER,
    total_answer_time               BIGINT,
    avatar_id                       INTEGER,
    current_answered_question_index INTEGER,
    CONSTRAINT pk_player PRIMARY KEY (id),
    CONSTRAINT fk_player_room FOREIGN KEY (room_code) REFERENCES game_room (room_code)
);

CREATE INDEX IF NOT EXISTS idx_player_room_code ON player (room_code);

-- Question: options is an @ElementCollection (see question_options), NOT a native array.
CREATE TABLE IF NOT EXISTS question
(
    id            VARCHAR(255) NOT NULL,
    text          VARCHAR(255),
    correct_index INTEGER,
    CONSTRAINT pk_question PRIMARY KEY (id)
);

-- Question.options: @ElementCollection<String> -> collection table (bag, no PK).
CREATE TABLE IF NOT EXISTS question_options
(
    question_id VARCHAR(255) NOT NULL,
    options     VARCHAR(255),
    CONSTRAINT fk_question_options_question FOREIGN KEY (question_id) REFERENCES question (id)
);

CREATE INDEX IF NOT EXISTS idx_question_options_question_id ON question_options (question_id);

-- PlayerAnswer: id is IDENTITY; player is @ManyToOne -> player(id) (VARCHAR(255)).
CREATE TABLE IF NOT EXISTS player_answer
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    player_id             VARCHAR(255),
    question_id           VARCHAR(255),
    selected_option_index INTEGER,
    correct               BOOLEAN,
    answer_time_ms        BIGINT,
    CONSTRAINT pk_player_answer PRIMARY KEY (id),
    CONSTRAINT fk_player_answer_player FOREIGN KEY (player_id) REFERENCES player (id)
);

CREATE INDEX IF NOT EXISTS idx_player_answer_player_id ON player_answer (player_id);

-- ---------------------------------------------------------------------------
-- Per-user learning data (synced from the Android client)
-- ---------------------------------------------------------------------------

-- UserWordProgress: word_id is the permanent numeric v18 word id (LOGICAL FK to
-- the trainvoc-words `words.id` — no SQL FK across databases).
CREATE TABLE IF NOT EXISTS user_word_progress
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id          BIGINT    NOT NULL,
    word_id          BIGINT    NOT NULL,
    last_reviewed    TIMESTAMP,
    next_review_date TIMESTAMP,
    easiness_factor  REAL      NOT NULL,
    interval_days    INTEGER   NOT NULL,
    repetitions      INTEGER   NOT NULL,
    is_favorite      BOOLEAN   NOT NULL,
    seconds_spent    INTEGER   NOT NULL,
    is_learned       BOOLEAN   NOT NULL,
    created_at       TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP,
    CONSTRAINT pk_user_word_progress PRIMARY KEY (id),
    CONSTRAINT uk_user_word UNIQUE (user_id, word_id),
    CONSTRAINT fk_user_word_progress_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_uwp_user_id ON user_word_progress (user_id);
CREATE INDEX IF NOT EXISTS idx_uwp_word_id ON user_word_progress (word_id);
CREATE INDEX IF NOT EXISTS idx_uwp_next_review ON user_word_progress (next_review_date);

-- UserWordStatistic: word_id is a LOGICAL cross-database FK (see above).
CREATE TABLE IF NOT EXISTS user_word_statistics
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id          BIGINT    NOT NULL,
    word_id          BIGINT    NOT NULL,
    correct_count    INTEGER   NOT NULL,
    wrong_count      INTEGER   NOT NULL,
    skipped_count    INTEGER   NOT NULL,
    last_answered_at TIMESTAMP,
    created_at       TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP,
    CONSTRAINT pk_user_word_statistics PRIMARY KEY (id),
    CONSTRAINT uk_user_word_stat UNIQUE (user_id, word_id),
    CONSTRAINT fk_user_word_statistics_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_uws_user_id ON user_word_statistics (user_id);
CREATE INDEX IF NOT EXISTS idx_uws_word_id ON user_word_statistics (word_id);

-- UserExamHistory.
CREATE TABLE IF NOT EXISTS user_exam_history
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id            BIGINT       NOT NULL,
    exam_id            VARCHAR(100) NOT NULL,
    exam_type          VARCHAR(50),
    completed_at       TIMESTAMP,
    score              INTEGER      NOT NULL,
    total_questions    INTEGER      NOT NULL,
    correct_answers    INTEGER      NOT NULL,
    time_spent_seconds INTEGER,
    level              VARCHAR(20),
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP,
    CONSTRAINT pk_user_exam_history PRIMARY KEY (id),
    CONSTRAINT fk_user_exam_history_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_ueh_user_id ON user_exam_history (user_id);
CREATE INDEX IF NOT EXISTS idx_ueh_completed_at ON user_exam_history (completed_at);

-- UserAchievement.
CREATE TABLE IF NOT EXISTS user_achievements
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id        BIGINT       NOT NULL,
    achievement_id VARCHAR(100) NOT NULL,
    progress       INTEGER      NOT NULL,
    max_progress   INTEGER      NOT NULL,
    is_unlocked    BOOLEAN      NOT NULL,
    unlocked_at    TIMESTAMP,
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP,
    CONSTRAINT pk_user_achievements PRIMARY KEY (id),
    CONSTRAINT uk_user_achievement UNIQUE (user_id, achievement_id),
    CONSTRAINT fk_user_achievements_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_ua_user_id ON user_achievements (user_id);
CREATE INDEX IF NOT EXISTS idx_ua_achievement_id ON user_achievements (achievement_id);

-- UserBackup: backup_id is @Column(unique = true).
CREATE TABLE IF NOT EXISTS user_backups
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT       NOT NULL,
    backup_id    VARCHAR(100) NOT NULL,
    storage_path VARCHAR(500),
    size_bytes   BIGINT,
    checksum     VARCHAR(64),
    backup_type  VARCHAR(50),
    is_encrypted BOOLEAN      NOT NULL,
    status       VARCHAR(20),
    created_at   TIMESTAMP    NOT NULL,
    completed_at TIMESTAMP,
    CONSTRAINT pk_user_backups PRIMARY KEY (id),
    CONSTRAINT uk_user_backups_backup_id UNIQUE (backup_id),
    CONSTRAINT fk_user_backups_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_ub_user_id ON user_backups (user_id);
CREATE INDEX IF NOT EXISTS idx_ub_created_at ON user_backups (created_at);

-- UserFeatureFlag.
CREATE TABLE IF NOT EXISTS user_feature_flags
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT       NOT NULL,
    flag_name  VARCHAR(100) NOT NULL,
    is_enabled BOOLEAN      NOT NULL,
    variant    VARCHAR(50),
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT pk_user_feature_flags PRIMARY KEY (id),
    CONSTRAINT uk_user_flag UNIQUE (user_id, flag_name),
    CONSTRAINT fk_user_feature_flags_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_uff_user_id ON user_feature_flags (user_id);
CREATE INDEX IF NOT EXISTS idx_uff_flag_name ON user_feature_flags (flag_name);

-- ---------------------------------------------------------------------------
-- SRS cross-device sync (SrsSchedule, @IdClass composite PK)
-- ---------------------------------------------------------------------------
-- word_id is a LOGICAL cross-database FK to words.id. user_id is the stringified
-- primary-DB user id (@Column length 128), a LOGICAL reference — NOT a SQL FK to
-- users.id (which is BIGINT). Instant columns are TIMESTAMP WITH TIME ZONE.
CREATE TABLE IF NOT EXISTS srs_schedule
(
    word_id           BIGINT                   NOT NULL,
    user_id           VARCHAR(128)             NOT NULL,
    due_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    stability         DOUBLE PRECISION         NOT NULL,
    difficulty        DOUBLE PRECISION         NOT NULL,
    last_reviewed_at  TIMESTAMP WITH TIME ZONE,
    card_state        VARCHAR(16)              NOT NULL,
    client_updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_srs_schedule PRIMARY KEY (word_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_srs_schedule_user_due ON srs_schedule (user_id, due_at);
CREATE INDEX IF NOT EXISTS idx_srs_schedule_user_id ON srs_schedule (user_id);

COMMIT;
